// <auto-generated />
using ASM2_AppDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM2_AppDev.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231209072559_AddDataToTable")]
    partial class AddDataToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM2_AppDev.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "So scary",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Description = "So cool",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Description = "So romance",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "So difficult",
                            Name = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
