// <auto-generated />
using ASM2_AppDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM2_AppDev.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231209083211_AddBook")]
    partial class AddBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM2_AppDev.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Anne",
                            CategoryId = 1,
                            Description = "Hello",
                            Price = 10.0,
                            Publisher = "Kim Dong",
                            Quantity = 10,
                            Title = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jane",
                            CategoryId = 3,
                            Description = "Hello",
                            Price = 15.0,
                            Publisher = "Kim Dong",
                            Quantity = 15,
                            Title = "Java Programming"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Billy",
                            CategoryId = 2,
                            Description = "Hello",
                            Price = 20.0,
                            Publisher = "Kim Dong",
                            Quantity = 20,
                            Title = "Python Programming"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jessica",
                            CategoryId = 4,
                            Description = "Hello",
                            Price = 15.0,
                            Publisher = "Kim Dong",
                            Quantity = 15,
                            Title = "C Programming"
                        });
                });

            modelBuilder.Entity("ASM2_AppDev.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "So scary",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Description = "So cool",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Description = "So romance",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "So difficult",
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("ASM2_AppDev.Models.Book", b =>
                {
                    b.HasOne("ASM2_AppDev.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
